* Following along with Machine Learning in Python tutorial
http://machinelearningmastery.com/machine-learning-in-python-step-by-step/

* Tangling
=C-c C-v t= tangles all code blocks in the file.  Pass a prefix
 argument to only tangle the current block.

* Bootstrap
Run with =./script/bootstrap=

** Requirements.txt
#+BEGIN_SRC python :tangle ./requirements.txt
  numpy==1.12.0
  scipy==0.18.1
  matplotlib==2.0.0
  pandas==0.19.2
  scikit-learn==0.18.1

#+END_SRC

** Python virtual environment

Install =python3= if it's not already installed.

#+BEGIN_SRC sh :tangle script/bootstrap :shebang "#!/bin/bash"
  echo "🌯  Updating homebrew to ensure dependencies are installed and upgraded"
  brew update

  if ! brew ls --versions python3 > /dev/null; then
     brew install python3
  fi

  if brew outdated | grep -q python3; then
      brew upgrade python3
  fi
#+END_SRC

Create the virtual env.

#+BEGIN_SRC sh :tangle script/bootstrap :shebang "#!/bin/bash"
  python3 -m venv ./venv
#+END_SRC

Install the requirements to the virtual environment.  If the user is
running =./script/bootstrap= from a shell that is not in the virtual
env, handle it and drop the user into a shell that is running the
virtual environment

#+BEGIN_SRC sh :tangle script/bootstrap :shebang "#!/bin/bash"
  if [ -z ${VIRTUAL_ENV+x} ]; then
      echo "🌯  You're not in the virutal env.  Dropping you into a shell with the virtual env activated."
      source ./venv/bin/activate/
      ./venv/bin/pip install -r ./requirements.txt
      /bin/bash -c ". ./venv/bin/activate; exec /bin/bash -i"
  else
      echo "🌯  Installing requirements to the virtual env"
      ./venv/bin/pip install -r ./requirements.txt
  fi
#+END_SRC

To activate the virtualenv in a shell =source venv/bin/activate=.

* Setup

Run =./script/setup= for initial setup or to return the project to its
initial state.

#+BEGIN_SRC sh :tangle script/setup :shebang "#!/bin/bash"
  rm -rf ./venv/
  script/bootstrap
#+END_SRC

* Update

Run =./script/update= after pulling to ensure that dependencies and
environment are up to date.

#+BEGIN_SRC sh :tangle script/update :shebang "#!/bin/bash"
  script/bootstrap
#+END_SRC

* Server

* Test

* CI Build

* Console
